# Generated by Django 3.0.5 on 2020-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('cover', models.TextField(verbose_name='文章封面')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('markdown_content', models.TextField(verbose_name='文章内容（markdown）')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('read_times', models.IntegerField()),
            ],
        ),
    ]
